CREATE  PROCEDURE [dbo].[P_GEN_CEVALDOM_OPER_WS_MM_MARCAENVIADA]
@NUMERO_OPERACION NUMERIC(36,0)
AS
UPDATE vGen_XML_CEVALDOM_MONEYMARKET
SET ENVIADO = 0
WHERE NUMERO_OPERACION = @NUMERO_OPERACION AND ENVIADO = 1

GO  

 
