USE DBRD_DB
GO

CREATE TRIGGER  TR_INSERTA_swoper_sync
ON siopel_owner.swoper
AFTER INSERT 
AS
INSERT INTO SIOPEL_INTERFACE_DB.siopel_owner.swoper_sync
(	clave
   ,CODIGODERE
   ,FECHA
   ,HORA
   ,NUMEROSECU
   ,codigodeti
   ,cupon
   ,numerocupo
   ,plazoopera
   ,moneda
   ,tipo
   ,codigoagen
   ,codigoage2
   ,CANTIDADOP
   ,PRECIOOPER
   ,PRECIOREFE
   ,TOPEBASE
   ,FLOTACION
   ,operaciono
   ,operaciond
   ,PRECIOCIER
   ,rueda
   ,opeorigen
   ,INTERES
   ,estado
   ,TASAOPER
   ,VALORIZACI
   ,modo
   ,memotec
   ,VALORIZAD
   ,ambiente
   ,mercado
   ,nroordenc
   ,codcomic
   ,nroordenv
   ,codcomiv
   ,ofertav
   ,ofertac
   ,tipogiro
   ,dia
   ,mes
   ,anio
   ,hh
   ,mm
   ,ss
   ,VIGENCIAT
   ,INDICADORC
   ,plazovta
   ,atributo
   ,precioidas
   ,agenmm
   ,age2mm
   ,brokeragem
   ,realocada
   ,secopreori
   ,secopre
   ,propia
   ,operador
   ,siespegtia
   ,sicantgtia
   ,siprtagtia
   ,sipteqgtia
   ,nefechemis
   ,nefechvto
   ,neperioint
   ,nemodinter
   ,neperiorei
   ,nemodreinv
   ,netasafaci
   ,nepremio
   ,tasaequinf
   ,nroordeinf
   ,fechaliq
   ,fechaliq2
   ,valorizac2
   ,valodolar2
   ,pata
   ,referencia
   ,descabrev
   ,especieori
   ,cuentacli
   ,NomContInt
   ,NomCustInt
   ,SECOPORVTA
   ,SECOPORCPA
   ,PorcGarant
   ,PorComiLic
   ,TipComiLic
   ,EnteLiq
   ,Pu
   ,ValVol
   ,ValVolD
   ,SumaVolOpe
   ,TextoCpa
   ,TextoVta
   ,MemoTecGen
   ,TituloBCRA
   ,CtaBCRA
   ,CtaBCRA2
   ,ESPECIEGEN
   ,ESPECIE
   ,DIASTRANS
   ,FEPROPACUP
   ,DIPROPACUP
   ,DIASVTOTIT
   ,FEULTCUPON
   ,FECHA2
   ,TIPOLIQ
   ,TipoOrdenC
   ,TipoOrdenV
   ,TipoMerca
   ,CANTOFECPA
   ,CANTOFEVTA
   ,PCIOOFVTA
   ,PCIOOFCPRA
   ,TasaPiso
   ,TasaTecho)
SELECT 
	clave
   ,CODIGODERE
   ,FECHA
   ,HORA
   ,NUMEROSECU
   ,codigodeti
   ,cupon
   ,numerocupo
   ,plazoopera
   ,moneda
   ,tipo
   ,codigoagen
   ,codigoage2
   ,CANTIDADOP
   ,PRECIOOPER
   ,PRECIOREFE
   ,TOPEBASE
   ,FLOTACION
   ,operaciono
   ,operaciond
   ,PRECIOCIER
   ,rueda
   ,opeorigen
   ,INTERES
   ,estado
   ,TASAOPER
   ,VALORIZACI
   ,modo
   ,memotec
   ,VALORIZAD
   ,ambiente
   ,mercado
   ,nroordenc
   ,codcomic
   ,nroordenv
   ,codcomiv
   ,ofertav
   ,ofertac
   ,tipogiro
   ,dia
   ,mes
   ,anio
   ,hh
   ,mm
   ,ss
   ,VIGENCIAT
   ,INDICADORC
   ,plazovta
   ,atributo
   ,precioidas
   ,agenmm
   ,age2mm
   ,brokeragem
   ,realocada
   ,secopreori
   ,secopre
   ,propia
   ,operador
   ,siespegtia
   ,sicantgtia
   ,siprtagtia
   ,sipteqgtia
   ,nefechemis
   ,nefechvto
   ,neperioint
   ,nemodinter
   ,neperiorei
   ,nemodreinv
   ,netasafaci
   ,nepremio
   ,tasaequinf
   ,nroordeinf
   ,fechaliq
   ,fechaliq2
   ,valorizac2
   ,valodolar2
   ,pata
   ,referencia
   ,descabrev
   ,especieori
   ,cuentacli
   ,NomContInt
   ,NomCustInt
   ,SECOPORVTA
   ,SECOPORCPA
   ,PorcGarant
   ,PorComiLic
   ,TipComiLic
   ,EnteLiq
   ,Pu
   ,ValVol
   ,ValVolD
   ,SumaVolOpe
   ,TextoCpa
   ,TextoVta
   ,MemoTecGen
   ,TituloBCRA
   ,CtaBCRA
   ,CtaBCRA2
   ,ESPECIEGEN
   ,ESPECIE
   ,DIASTRANS
   ,FEPROPACUP
   ,DIPROPACUP
   ,DIASVTOTIT
   ,FEULTCUPON
   ,FECHA2
   ,TIPOLIQ
   ,TipoOrdenC
   ,TipoOrdenV
   ,TipoMerca
   ,CANTOFECPA
   ,CANTOFEVTA
   ,PCIOOFVTA
   ,PCIOOFCPRA
   ,TasaPiso
   ,TasaTecho
FROM INSERTED
-- siopel_owner.swoper_sync
