USE [SIOPEL_INTERFACE_DB]
GO


 ALTER  VIEW [dbo].[vGen_XML_CEVALDOM_MONEYMARKET1]
 AS
SELECT
	'<?xml version="1.0" encoding="UTF-8"?><SolOperaciones><SOLOPER><Negociacion><VENDEDOR>' + ID_DEPOSITANTE_VENDEDOR + '</VENDEDOR><COMPRADOR>' + ID_DEPOSITANTE_COMPRADOR + '</COMPRADOR><MECANISMO>BVRD</MECANISMO><MODALIDAD>1</MODALIDAD><REFERENCIA>' + NUMERO_OPERACION + '</REFERENCIA><PACTADA>' + FECHA_TRANSACCION + '</PACTADA><OBSERVACIONES>' + OBSERVACIONES + '</OBSERVACIONES></Negociacion><Liquidacion><Contado><ESQUEMA>1</ESQUEMA><TIPO>1</TIPO><LIQUIDACION>' + +FECHA_TRANSACCION + '</LIQUIDACION><ISIN>' + CODIGO_ISIN + '</ISIN><MONEDA>' + ID_MONEDA_LIQUIDACION + '</MONEDA><TITULOS>' + CAST(CANTIDAD_TITULOS AS VARCHAR) + '</TITULOS><PRECIO>' + CAST(PRECIO_PRIMA AS VARCHAR) + '</PRECIO><IMPORTE>' + CAST(IMPORTE_BRUTO AS VARCHAR) + '</IMPORTE></Contado></Liquidacion><VERIFICADOR>' +
	CAST([dbo].[fn_DigitoVerificadorCevaldom](
	ID_DEPOSITANTE_VENDEDOR + '' +
	ID_DEPOSITANTE_COMPRADOR + '' +
	'BVRD' + '' +
	'1' + '' +
	CAST(NUMERO_OPERACION AS VARCHAR) + '' +
	CAST(FECHA_TRANSACCION AS VARCHAR) + '' + 
	CAST(OBSERVACIONES AS VARCHAR) + '' +
	CAST(ESQUEMA AS VARCHAR) + '' +
	CAST(TIPO AS VARCHAR) + '' +	
	CAST(FECHA_TRANSACCION AS VARCHAR) + '' +
	CAST(CODIGO_ISIN AS VARCHAR) + '' +
	CAST(ID_MONEDA_LIQUIDACION AS VARCHAR) + '' +
	CAST(CANTIDAD_TITULOS AS VARCHAR) + '' +
	CAST(PRECIO_PRIMA AS VARCHAR) + '' +
	CAST(IMPORTE_BRUTO AS VARCHAR)) AS VARCHAR)

	+ '</VERIFICADOR></SOLOPER></SolOperaciones>' AS CADENA
   ,* ,
   [dbo].[fn_DigitoVerificadorCevaldom](
    ID_DEPOSITANTE_VENDEDOR + '' +
	ID_DEPOSITANTE_COMPRADOR + '' +
	'BVRD' + '' +
	'1' + '' +
	CAST(NUMERO_OPERACION AS VARCHAR) + '' +
	CAST(FECHA_TRANSACCION AS VARCHAR) + '' +  
	CAST(OBSERVACIONES AS VARCHAR) + '' +
	CAST(ESQUEMA AS VARCHAR) + '' +
	CAST(TIPO AS VARCHAR) + '' +	
	CAST(FECHA_TRANSACCION AS VARCHAR) + '' +
	CAST(CODIGO_ISIN AS VARCHAR) + '' +
	CAST(ID_MONEDA_LIQUIDACION AS VARCHAR) + '' +
	CAST(CANTIDAD_TITULOS AS VARCHAR) + '' +
	CAST(PRECIO_PRIMA AS VARCHAR) + '' +
	CAST(IMPORTE_BRUTO AS VARCHAR) ) AS PRUEBA 
FROM vGen_XML_CEVALDOM_MONEYMARKET

GO
 

SELECT * FROM vGen_XML_CEVALDOM_MONEYMARKET1
