ALTER PROCEDURE P_GEN_CEVALDOM_OPER_WS_MONEYMARKET
@NUMERO_OPERACION NUMERIC(36,0)
AS
SELECT * FROM  vGen_XML_CEVALDOM_FORMAT_MONEYMARKET1 
WHERE NUMERO_OPERACION = @NUMERO_OPERACION -- 19030527788
GO

P_GEN_CEVALDOM_OPER_WS_MONEYMARKET  19030527788

 