USE [SIOPEL_INTERFACE_DB]
GO


ALTER   VIEW [dbo].[vGen_XML_CEVALDOM_MONEYMARKET1]
AS
SELECT
	--<?xml version="1.0" encoding="UTF-8"?><SolOperaciones>
	'<SOLOPER><Negociacion>   
			<ORIGEN>' + ORIGEN + '</ORIGEN>
			<VENDEDOR>' + ID_DEPOSITANTE_VENDEDOR + '</VENDEDOR>
			<COMPRADOR>' + ID_DEPOSITANTE_COMPRADOR + '</COMPRADOR>
			<MECANISMO>BVRD</MECANISMO>
			<MODALIDAD>' + MODALIDAD + '</MODALIDAD>
			<REFERENCIA>' + NUMERO_OPERACION + '</REFERENCIA>
			<ACORDADA>' + FECHA_TRANSACCION + '</ACORDADA>
			<HORA>' +
	CASE
		WHEN HORA > 12 THEN '0' +
			SUBSTRING([dbo].[format_date](FECHA_TRANSACCION + ' ' + HORA + ':' + MINUTO + ':' + SEGUNDO, 'YYYY-MM-DD 12HH:MI:SS AMPM'), 12, 11)
		ELSE SUBSTRING([dbo].[format_date](FECHA_TRANSACCION + ' ' + HORA + ':' + MINUTO + ':' + SEGUNDO, 'YYYY-MM-DD 12HH:MI:SS AMPM'), 12, 11)
	END + '</HORA>
			<OBSERVACIONES>' + OBSERVACIONES + '</OBSERVACIONES>
		  </Negociacion>
		  <Liquidacion>
			<Contado> 
			 <LIQUIDACION>' + +FECHA_LIQUIDACION + '</LIQUIDACION>
			 <ISIN>' + codigo_isin + '</ISIN>
 			 <FACIAL>' + CAST(FACIAL AS VARCHAR) + '</FACIAL>
			 <LIMPIO>' + CAST(LIMPIO AS VARCHAR) + '</LIMPIO>
			 <SUCIO>' + CAST(SUCIO AS VARCHAR) + '</SUCIO>
			 <RENDIMIENTO>' + CAST(RENDIMIENTO AS VARCHAR) + '</RENDIMIENTO>
			 <IMPORTE>' + CAST(IMPORTE_BRUTO AS VARCHAR) + '</IMPORTE>
			</Contado>  
			 <Plazo>
			  <DIAS>' + CAST(DIAS_PLAZO AS VARCHAR) + '</DIAS>
			  <LIMPIO>' + CAST(LIMPIO_PLAZO AS VARCHAR) + '</LIMPIO>
			  <SUCIO>' + CAST(SUCIO_PLAZO AS VARCHAR) + '</SUCIO>
			  <RENDIMIENTO>' + CAST(RENDIMIENTO_PLAZO AS VARCHAR) + '</RENDIMIENTO>
			  <IMPORTE>' + CAST(IMPORTE_PLAZO AS VARCHAR) + '</IMPORTE>
			 </Plazo>
		 </Liquidacion>
		 <VERIFICADOR>' +
	-- <?xml version=\"1.0\" encoding=\"UTF - 8\" ?><SolOperaciones><SOLOPER><Negociacion><VENDEDOR>JMMB</VENDEDOR>	    <COMPRADOR>JMMB							  </COMPRADOR><MECANISMO>BVRD</MECANISMO><MODALIDAD>1</MODALIDAD><REFERENCIA>19030527788			</REFERENCIA><PACTADA>05/03/2019			    </PACTADA><OBSERVACIONES>CONTADO			</OBSERVACIONES></Negociacion><Liquidacion><Contado><ESQUEMA>1</ESQUEMA><TIPO>1</TIPO><LIQUIDACION>05/03/2019				  </LIQUIDACION><ISIN>DO8013900121		 </ISIN><MONEDA>USD							 </MONEDA><TITULOS>2										</TITULOS><PRECIO>1055.714967						   </PRECIO><IMPORTE>2111.43							   </IMPORTE></Contado></Liquidacion><VERIFICADOR>64818</VERIFICADOR></SOLOPER></SolOperaciones>
	CONVERT(VARCHAR(8000), [dbo].[fn_DigitoVerificadorCevaldom](
	ORIGEN + '' +
	ID_DEPOSITANTE_VENDEDOR + '' +
	ID_DEPOSITANTE_COMPRADOR + '' +
	'BVRD' + '' +
	CAST(MODALIDAD AS VARCHAR) + '' +
	CAST(NUMERO_OPERACION AS VARCHAR) + '' +
	CAST(FECHA_TRANSACCION AS VARCHAR) + '' +
	--CAST(substring( [dbo].[format_date](FECHA_TRANSACCION+' ' +HORA +':' + MINUTO+':' +SEGUNDO, 'YYYY-MM-DD 12HH:MI:SS AMPM'),12,11) AS VARCHAR) + '' + 
	CASE
		WHEN HORA > 12 THEN '0' +
			SUBSTRING([dbo].[format_date](FECHA_TRANSACCION + ' ' + HORA + ':' + MINUTO + ':' + SEGUNDO, 'YYYY-MM-DD 12HH:MI:SS AMPM'), 12, 11)
		ELSE SUBSTRING([dbo].[format_date](FECHA_TRANSACCION + ' ' + HORA + ':' + MINUTO + ':' + SEGUNDO, 'YYYY-MM-DD 12HH:MI:SS AMPM'), 12, 11)
	END + '' +
	CAST(OBSERVACIONES AS VARCHAR) + '' +
	CAST(FECHA_LIQUIDACION AS VARCHAR) + '' +
	CAST(codigo_isin AS VARCHAR) + '' +
	CAST(FACIAL AS VARCHAR) + '' +
	CAST(LIMPIO AS VARCHAR) + '' +
	CAST(SUCIO AS VARCHAR) + '' +
	CAST(RENDIMIENTO AS VARCHAR) + '' +
	CAST(IMPORTE_BRUTO AS VARCHAR) + '' +
	CAST(DIAS_PLAZO AS VARCHAR) + '' +
	CAST(LIMPIO_PLAZO AS VARCHAR) + '' +
	CAST(SUCIO_PLAZO AS VARCHAR) + '' +
	CAST(RENDIMIENTO_PLAZO AS VARCHAR) + '' +
	CAST(IMPORTE_PLAZO AS VARCHAR)))
	+ '</VERIFICADOR></SOLOPER>' AS CADENA --</SolOperaciones>
	/* ,[dbo].[fn_DigitoVerificadorCevaldom](ID_DEPOSITANTE_VENDEDOR) + ''
     + [dbo].[fn_DigitoVerificadorCevaldom](ID_DEPOSITANTE_COMPRADOR) + '' 
     + [dbo].[fn_DigitoVerificadorCevaldom]('BVRD') + '' 
  
     + FECHA_TRANSACCION + '' + +FECHA_TRANSACCION + '' + codigo_isin + '' + ID_MONEDA_LIQUIDACION + '' + CAST(CANTIDAD_TITULOS AS VARCHAR) + '' + CAST(PRECIO_PRIMA AS VARCHAR) + '' + CAST(IMPORTE_BRUTO AS VARCHAR) AS VERIFICADOR
     */
   ,*
FROM vGen_XML_CEVALDOM_MONEYMARKET


GO


