USE [SIOPEL_INTERFACE_DB]
GO


ALTER  PROCEDURE [dbo].[P_GEN_CEVALDOM_OPER_WS_MM_MARCAENVIADA]
@NUMERO_OPERACION NUMERIC(36,0)
AS
SET DATEFORMAT DMY

UPDATE vGen_XML_CEVALDOM_MONEYMARKET
SET ENVIADO = 1
WHERE NUMERO_OPERACION = @NUMERO_OPERACION
AND ENVIADO = 0

GO

P_GEN_CEVALDOM_OPER_WS_MM_MARCAENVIADA -1


 
