USE [SIOPEL_INTERFACE_DB]
GO
 

CREATE TABLE [dbo].[CodigoAccesoCevaldom](
	[CODIGO] [int] NOT NULL,
	[NUMERO] [int] NOT NULL,
 CONSTRAINT [PK_CodigoAccesoCevaldom] PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC,
	[NUMERO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


