USE [SIOPEL_INTERFACE_DB]
GO
 
 
CREATE VIEW [dbo].[VAOP06AS400]
AS
SELECT
	*
   ,CASE
		WHEN CAST(operAS400.CTASELV06 AS INT) = 0 --AND AOP.ImportePlazo IS NULL 
		THEN 1
		ELSE CAST(operAS400.CTASELV06 AS INT)
	END AS TipoSolicitud
FROM OPENQUERY(N33, 'SELECT * FROM MAEPROD.DB031.AOP06 ') operAS400
GO


